package edu.usc.model;
// Generated 19:47:48 05-10-2011 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Posts generated by hbm2java
 */
public class Posts  implements java.io.Serializable {


     private long pid;
     private Users users;
     private BigDecimal place;
     private Date time;
     private String title;
     private String photo;
     private Set commentses = new HashSet(0);

    public Posts() {
    }

	
    public Posts(long pid, Users users, BigDecimal place, Date time, String title) {
        this.pid = pid;
        this.users = users;
        this.place = place;
        this.time = time;
        this.title = title;
    }
    public Posts(long pid, Users users, BigDecimal place, Date time, String title, String photo, Set commentses) {
       this.pid = pid;
       this.users = users;
       this.place = place;
       this.time = time;
       this.title = title;
       this.photo = photo;
       this.commentses = commentses;
    }
   
    public long getPid() {
        return this.pid;
    }
    
    public void setPid(long pid) {
        this.pid = pid;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public BigDecimal getPlace() {
        return this.place;
    }
    
    public void setPlace(BigDecimal place) {
        this.place = place;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }




}


