package edu.usc.model;
// Generated 19:47:48 05-10-2011 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private long cid;
     private Users users;
     private String text;
     private Date time;
     private Set postses = new HashSet(0);

    public Comments() {
    }

	
    public Comments(long cid, Users users, String text, Date time) {
        this.cid = cid;
        this.users = users;
        this.text = text;
        this.time = time;
    }
    public Comments(long cid, Users users, String text, Date time, Set postses) {
       this.cid = cid;
       this.users = users;
       this.text = text;
       this.time = time;
       this.postses = postses;
    }
   
    public long getCid() {
        return this.cid;
    }
    
    public void setCid(long cid) {
        this.cid = cid;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Set getPostses() {
        return this.postses;
    }
    
    public void setPostses(Set postses) {
        this.postses = postses;
    }




}


