package edu.usc.model;
// Generated 19:47:48 05-10-2011 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private long uid;
     private String firstname;
     private String lastname;
     private Set usersesForUidFrom = new HashSet(0);
     private Set usersesForUidTo = new HashSet(0);
     private Set commentses = new HashSet(0);
     private Set postses = new HashSet(0);

    public Users() {
    }

	
    public Users(long uid, String firstname, String lastname) {
        this.uid = uid;
        this.firstname = firstname;
        this.lastname = lastname;
    }
    public Users(long uid, String firstname, String lastname, Set usersesForUidFrom, Set usersesForUidTo, Set commentses, Set postses) {
       this.uid = uid;
       this.firstname = firstname;
       this.lastname = lastname;
       this.usersesForUidFrom = usersesForUidFrom;
       this.usersesForUidTo = usersesForUidTo;
       this.commentses = commentses;
       this.postses = postses;
    }
   
    public long getUid() {
        return this.uid;
    }
    
    public void setUid(long uid) {
        this.uid = uid;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Set getUsersesForUidFrom() {
        return this.usersesForUidFrom;
    }
    
    public void setUsersesForUidFrom(Set usersesForUidFrom) {
        this.usersesForUidFrom = usersesForUidFrom;
    }
    public Set getUsersesForUidTo() {
        return this.usersesForUidTo;
    }
    
    public void setUsersesForUidTo(Set usersesForUidTo) {
        this.usersesForUidTo = usersesForUidTo;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getPostses() {
        return this.postses;
    }
    
    public void setPostses(Set postses) {
        this.postses = postses;
    }
}


